[package]
name = "wayafknext-monitor"
version = "0.1.0"
edition = "2024"
authors = ["MuffinTastic <contact@muffintastic.dev>"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[dependencies]
